[versions]
conventions = "0.1.8"

slf4j = "2.0.18"
panama-android = "v0.1.3"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

panama-android-core = { module = "io.github.vova7878.panama:Core", version.ref = "panama-android" }

[plugins]
conventions-kmp = { id = "dev.silenium.gradle.conventions.kmp", version.ref = "conventions" }
